general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgb(0080ff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text = <span foreground="##cccccc">Password...</span>
    check_color = rgb(00ff00)
    fail_color = rgb(ff0000)
    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(ffffff)
    font_size = 100
    font_family = sans-serif
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi $USER
    color = rgb(cccccc)
    font_size = 25
    font_family = sans-serif
    position = 0, 50
    halign = center
    valign = center
}
