preload = ~/.config/hypr/wallpapers/wallpaper.png
# Set wallpaper for all monitors (use monitor name for specific monitor)
wallpaper = ,~/.config/hypr/wallpapers/wallpaper.png

# Optionally disable IPC if you don't need dynamic wallpaper changess
ipc = off
